name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    
    steps:
      - uses: actions/checkout@v4
        with:
          path: 'Icaros_hibrido'  # ← Garante a estrutura correta

      - name: Verify directory structure
        run: |
          echo "Estrutura completa:"
          ls -R
          echo "Verificando frontend:"
          ls -la Icaros_hibrido/front_icaros/my-project/package-lock.json
          echo "Verificando backend:"
          ls -la Icaros_hibrido/Icaros_hibrido/package-lock.json

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'
          cache-dependency-path: |
            Icaros_hibrido/front_icaros/my-project/package-lock.json
            Icaros_hibrido/Icaros_hibrido/package-lock.json

      # Frontend
      - name: Install frontend dependencies
        working-directory: Icaros_hibrido/front_icaros/my-project
        run: npm ci

      - name: Run frontend lint
        working-directory: Icaros_hibrido/front_icaros/my-project
        run: npm run lint

      # Backend
      - name: Install backend dependencies
        working-directory: Icaros_hibrido/Icaros_hibrido  # ← Caminho corrigido
        run: npm ci

      - name: Run backend lint
        working-directory: Icaros_hibrido/Icaros_hibrido
        run: npm run lintgit commit --allow-empty -m "Test CI paths"
git push