name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install frontend dependencies
        working-directory: front_icaros/my-project
        run: npm ci

      - name: Run frontend lint
        working-directory: front_icaros/my-project
        run: npm run lint

      - name: Run frontend prettier check
        working-directory: front_icaros/my-project
        run: npx prettier . --check

      - name: Run frontend tests
        working-directory: front_icaros/my-project
        run: npm test -- --watchAll=false

      - name: Install backend dependencies
        working-directory: icaros_hibrido
        run: npm ci

      - name: Run backend lint
        working-directory: icaros_hibrido
        run: npm run lint

      - name: Run backend prettier check
        working-directory: icaros_hibrido
        run: npx prettier . --check

      - name: Run backend tests
        working-directory: icaros_hibrido
        run: npm test
