name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4

      - name: Verify lock files
        run: |
          if [ ! -f front_icaros/my-project/package-lock.json ]; then
            echo "::error::Frontend lock file not found!"
            exit 1
          fi
          if [ ! -f icaros_hibrido/package-lock.json ]; then
            echo "::error::Backend lock file not found!"
            exit 1
          fi

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: |
            front_icaros/my-project/package-lock.json
            icaros_hibrido/package-lock.json

      # Frontend
      - name: Install frontend dependencies
        working-directory: front_icaros/my-project
        run: npm ci --audit=false

      - name: Run frontend lint
        working-directory: front_icaros/my-project
        run: npm run lint

      - name: Run frontend format check
        working-directory: front_icaros/my-project
        run: npm run check-format

      - name: Run frontend tests
        working-directory: front_icaros/my-project
        run: npm test -- --watchAll=false --ci

      # Backend
      - name: Install backend dependencies
        working-directory: icaros_hibrido
        run: npm ci --audit=false

      - name: Run backend lint
        working-directory: icaros_hibrido
        run: npm run lint

      - name: Run backend format check
        working-directory: icaros_hibrido
        run: npm run check-format

      - name: Run backend tests
        working-directory: icaros_hibrido
        run: npm test -- --ci